const COUNTRY_CODES: Record<string, string> = {
  'Afghanistan': 'af',
  'Albania': 'al',
  'Argentina': 'ar',
  'Australia': 'au',
  'Austria': 'at',
  'Bahrain': 'bh',
  'Belgium': 'be',
  'Brazil': 'br',
  'Bulgaria': 'bg',
  'Canada': 'ca',
  'Chile': 'cl',
  'Colombia': 'co',
  'Croatia': 'hr',
  'Czech Republic': 'cz',
  'Denmark': 'dk',
  'Egypt': 'eg',
  'Estonia': 'ee',
  'Finland': 'fi',
  'France': 'fr',
  'Germany': 'de',
  'Ghana': 'gh',
  'Greece': 'gr',
  'Hungary': 'hu',
  'India': 'in',
  'Indonesia': 'id',
  'Iraq': 'iq',
  'Ireland': 'ie',
  'Israel': 'il',
  'Italy': 'it',
  'Japan': 'jp',
  'Jordan': 'jo',
  'Kenya': 'ke',
  'Kuwait': 'kw',
  'Latvia': 'lv',
  'Lebanon': 'lb',
  'Lithuania': 'lt',
  'Malaysia': 'my',
  'Mexico': 'mx',
  'Morocco': 'ma',
  'NATO': 'nato',
  'Netherlands': 'nl',
  'New Zealand': 'nz',
  'Nigeria': 'ng',
  'Norway': 'no',
  'Oman': 'om',
  'Pakistan': 'pk',
  'Peru': 'pe',
  'Philippines': 'ph',
  'Poland': 'pl',
  'Portugal': 'pt',
  'Qatar': 'qa',
  'Republic of Korea': 'kr',
  'Romania': 'ro',
  'Saudi Arabia': 'sa',
  'Singapore': 'sg',
  'Slovakia': 'sk',
  'Slovenia': 'si',
  'South Africa': 'za',
  'Spain': 'es',
  'Sweden': 'se',
  'Switzerland': 'ch',
  'Taiwan': 'tw',
  'Thailand': 'th',
  'Tunisia': 'tn',
  'Turkey': 'tr',
  'Ukraine': 'ua',
  'United Arab Emirates': 'ae',
  'United Kingdom': 'gb',
  'Vietnam': 'vn',
  'Zambia': 'zm',
}

export function getFlagUrl(country: string): string | null {
  const code = COUNTRY_CODES[country]
  if (!code || code === 'nato') return null
  return `https://flagcdn.com/w80/${code}.png`
}
