export const COUNTRY_NAME_TO_ISO3: Record<string, string> = {
  "Afghanistan": "AFG",
  "Albania": "ALB",
  "Argentina": "ARG",
  "Australia": "AUS",
  "Austria": "AUT",
  "Bahrain": "BHR",
  "Bangladesh": "BGD",
  "Belgium": "BEL",
  "Bosnia and Herzegovina": "BIH",
  "Brazil": "BRA",
  "Brunei": "BRN",
  "Bulgaria": "BGR",
  "Canada": "CAN",
  "Chile": "CHL",
  "Colombia": "COL",
  "Croatia": "HRV",
  "Czech Republic": "CZE",
  "Denmark": "DNK",
  "Ecuador": "ECU",
  "Egypt": "EGY",
  "Estonia": "EST",
  "Finland": "FIN",
  "France": "FRA",
  "Georgia": "GEO",
  "Germany": "DEU",
  "Ghana": "GHA",
  "Greece": "GRC",
  "Guyana": "GUY",
  "Hungary": "HUN",
  "India": "IND",
  "Indonesia": "IDN",
  "Iraq": "IRQ",
  "Ireland": "IRL",
  "Israel": "ISR",
  "Italy": "ITA",
  "Japan": "JPN",
  "Jordan": "JOR",
  "Kazakhstan": "KAZ",
  "Kenya": "KEN",
  "Kosovo": "XKX",
  "Kuwait": "KWT",
  "Latvia": "LVA",
  "Lebanon": "LBN",
  "Libya": "LBY",
  "Lithuania": "LTU",
  "Luxembourg": "LUX",
  "Malaysia": "MYS",
  "Mexico": "MEX",
  "Montenegro": "MNE",
  "Morocco": "MAR",
  "Netherlands": "NLD",
  "New Zealand": "NZL",
  "Nigeria": "NGA",
  "North Macedonia": "MKD",
  "Norway": "NOR",
  "Oman": "OMN",
  "Pakistan": "PAK",
  "Peru": "PER",
  "Philippines": "PHL",
  "Poland": "POL",
  "Portugal": "PRT",
  "Qatar": "QAT",
  "Republic of Korea": "KOR",
  "Romania": "ROU",
  "Saudi Arabia": "SAU",
  "Singapore": "SGP",
  "Slovakia": "SVK",
  "Slovenia": "SVN",
  "Spain": "ESP",
  "Sweden": "SWE",
  "Switzerland": "CHE",
  "Taiwan": "TWN",
  "Thailand": "THA",
  "Tunisia": "TUN",
  "Turkey": "TUR",
  "Türkiye": "TUR",
  "Ukraine": "UKR",
  "United Arab Emirates": "ARE",
  "United Kingdom": "GBR",
  "United States": "USA",
  "Uruguay": "URY",
  "Vietnam": "VNM",
  "Zambia": "ZMB",
}

// ISO 3166-1 numeric → ISO3 mapping
// world-atlas topojson uses numeric IDs as geo.id — no ISO_A3 in properties
export const NUMERIC_TO_ISO3: Record<string, string> = {
  "4": "AFG", "8": "ALB", "12": "DZA", "24": "AGO", "32": "ARG",
  "36": "AUS", "40": "AUT", "48": "BHR", "50": "BGD", "56": "BEL",
  "64": "BTN", "68": "BOL", "70": "BIH", "76": "BRA", "96": "BRN",
  "100": "BGR", "104": "MMR", "116": "KHM", "120": "CMR", "124": "CAN",
  "144": "LKA", "152": "CHL", "156": "CHN", "158": "TWN", "170": "COL",
  "178": "COG", "180": "COD", "188": "CRI", "191": "HRV", "192": "CUB",
  "196": "CYP", "203": "CZE", "204": "BEN", "208": "DNK", "214": "DOM",
  "218": "ECU", "231": "ETH", "233": "EST", "246": "FIN", "250": "FRA",
  "266": "GAB", "268": "GEO", "276": "DEU", "288": "GHA", "300": "GRC",
  "320": "GTM", "324": "GIN", "328": "GUY", "340": "HND", "348": "HUN",
  "356": "IND", "360": "IDN", "364": "IRN", "368": "IRQ", "372": "IRL",
  "376": "ISR", "380": "ITA", "384": "CIV", "388": "JAM", "392": "JPN",
  "400": "JOR", "404": "KEN", "408": "PRK", "410": "KOR", "414": "KWT",
  "418": "LAO", "422": "LBN", "428": "LVA", "430": "LBR", "434": "LBY",
  "440": "LTU", "442": "LUX", "458": "MYS", "466": "MLI", "484": "MEX",
  "496": "MNG", "499": "MNE", "504": "MAR", "508": "MOZ", "512": "OMN",
  "516": "NAM", "524": "NPL", "528": "NLD", "540": "NCL", "554": "NZL",
  "558": "NIC", "562": "NER", "566": "NGA", "578": "NOR", "586": "PAK",
  "591": "PAN", "598": "PNG", "600": "PRY", "604": "PER", "608": "PHL",
  "616": "POL", "620": "PRT", "630": "PRI", "634": "QAT", "642": "ROU",
  "646": "RWA", "682": "SAU", "686": "SEN", "694": "SLE", "702": "SGP",
  "703": "SVK", "704": "VNM", "705": "SVN", "706": "SOM", "710": "ZAF",
  "716": "ZWE", "724": "ESP", "729": "SDN", "740": "SUR", "752": "SWE",
  "756": "CHE", "760": "SYR", "762": "TJK", "764": "THA", "768": "TGO",
  "780": "TTO", "784": "ARE", "788": "TUN", "792": "TUR", "800": "UGA",
  "804": "UKR", "807": "MKD", "818": "EGY", "826": "GBR", "834": "TZA",
  "840": "USA", "858": "URY", "860": "UZB", "862": "VEN", "887": "YEM",
  "894": "ZMB",
}

export function getISO3(countryName: string | null): string | null {
  if (!countryName) return null
  return COUNTRY_NAME_TO_ISO3[countryName] ?? null
}
